---
title: "climate_NWT_DataPrep"
author: "Jean Marchal"
date: "13 March 2019"
output: pdf_document
---

# Overview

Provide an overview of what the module does / how to use the module.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
library(SpaDES)

setPaths(
  cachePath = file.path("../cache"),
  modulePath = file.path("..")
)
getPaths() # shows where the 4 relevant paths are

times <- list(start = 2011, end = 2100)

parameters <- list(
  climate_NWT_DataPrep = list(
    rcp = 45, # 45 or 85
    gcm = "CanESM2" # One of CanESM2, GFDL-CM3, HadGEM2-ES, MPI-ESM-LR  
  )
  #.progress = list(type = "text", interval = 1), # for a progress bar
  ## If there are further modules, each can have its own set of parameters:
  #module1 = list(param1 = value1, param2 = value2),
  #module2 = list(param1 = value1, param2 = value2)
)
modules <- list("climate_NWT_DataPrep")
objects <- list()
inputs <- list()
outputs <- list()

mySim <- simInit(
  times = times, 
  params = parameters, 
  modules = modules, 
  objects = objects
)

mySimOut <- spades(mySim)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("climate_NWT_DataPrep", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

