---
title: "Simulting climate change and fire regime: implications for boreal caribou and landbird communities in the Northwest Territories"
subtitle: "From data to decisions in SpaDES: an integrated projection project for the Northwest Territories"
authors: "Tati Micheletti^1^", "Steve Cumming^2^", "Frances Stewart^3^", "Diana Stralberg^4^", "Eliot McIntire^3,1^" "Jean Marchal^4^",
"Ian Eddy^3^", "Mario van Telgen^2^", "Ceres Barros^1^", "Ana Raymundo^2^"
affiliations: "^1^ University of British Columbia", "^2^ University of Laval", "^3^ Natural Resources Canada, Canadian Forest Service",
"^4^ University of Alberta", "^4^WavX Inc."
date: "Draft last revised 3/31/2019"
 html_document:
    keep_md: yes
    toc: yes
    toc_depth: 5
 pdf_document:
    keep_md: yes
    toc: yes
    toc_depth: 5
---


```{r github, include=FALSE, eval = FALSE}
knitr::opts_chunk$set(echo = FALSE)

update.packages(checkBuilt = TRUE)
devtools::install_github("PredictiveEcology/reproducible@development")
devtools::install_github("achubaty/amc@development")
devtools::install_github("PredictiveEcology/pemisc@development")
devtools::install_github("PredictiveEcology/map@development")
devtools::install_github("PredictiveEcology/LandR@development") # Updates SpaDES.tools and SpaDES.core quickPlot
devtools::install_github("ianmseddy/LandR.CS@master") # Climate sensitivity in LandR

```

## Setting up directories and paths for the simulation

First, make sure you have the correct R version. These models were created using 
the following R version and might not workcorrectly in other versions:

```{r rVersion}

message(paste0("This model uses R version 3.5.2 (2018-12-20). Your session runs ", 
               sessionInfo()[["R.version"]][["version.string"]]))

```

Second, load all needed dependencies. 

```{r libraries}

library("LandR")
library("SpaDES")
library("raster")
library("plyr"); library("dplyr")
library("magrittr") # for piping

```


### Running `Caribous` using the succession model

```{r birds}

# Set the WD to the NWT folder if not inside a project
# setwd("/mnt/data/Micheletti/NWT")

dayOfRecording <- today <- toupper(format(Sys.time(), "%d%b%y"))

isTEST <- TRUE

if (isTEST){
    dayOfRecording <- "19MAR19"
}

message("Your current temporary directory is ", tempdir())

create <- if (isTEST) NULL else TRUE 
checkInputPath <- tryCatch(checkPath(file.path(getwd(), "outputs", dayOfRecording)), error = function(e) NULL)
if (is.null(checkInputPath)){
  inpPath <- tempdir()
} else {
  inpPath <- checkInputPath
}

checkOutputPath <- tryCatch(checkPath(file.path(getwd(), "outputs", today), create = create), error = function(e) NULL)
if (is.null(checkOutputPath)){
  outPath <- tempdir()
} else {
  outPath <- checkOutputPath
}

setPaths(modulePath = file.path(getwd(), "modules"), 
         cachePath = file.path(getwd(), "cache"),
         inputPath = inpPath, 
         outputPath = outPath)

getPaths() # shows where the 4 relevant paths are

invisible(sapply(X = list.files(file.path(getwd(), "functions"), full.names = TRUE), FUN = source))

Edehzhie.url <- "https://drive.google.com/open?id=1o2VamVILFx8SHqMCPC8bmjM8pkr5fsks"

studyAreaEde <- Cache(prepInputs,
                           url = Edehzhie.url,
                           destinationPath = getPaths()$inputPath[[1]],
                           userTags = "edeSA",
                           omitArgs = c("destinationPath"))

rasterToMatch <- Cache(prepInputs, url = "https://drive.google.com/open?id=1fo08FMACr_aTV03lteQ7KsaoN9xGx1Df", 
                            studyArea = studyAreaEde,
                            targetFile = "RTM.tif", destinationPath = getPaths()$inputPath[[1]], 
                       filename2 = NULL,
                            userTags = "edeRTM",
                            omitArgs = c("destinationPath", "filename2"))

times <- list(start = 0, end = 100)

modules <- list("caribouRSF")

cloudFolderID <- "https://drive.google.com/open?id=1PoEkOkg_ixnAdDqqTQcun77nUvkEHDc0"

waterRaster <- prepInputs(url = "https://drive.google.com/open?id=1nPd03gaVXkkaHorirR4UhYrDi95ZgyJM",
                          targetFile = "waterRasterNW.tif", 
                          studyArea = studyAreaEde, 
                          rasterToMatch = rasterToMatch, 
                          destinationPath = getPaths()$inputPath, 
                          filename2 = "waterRasterNW.tif", overwrite = TRUE)


.objects <- list(
  "rasterToMatch" = rasterToMatch,
  "cloudFolderID" = cloudFolderID,
  "studyArea" = studyAreaEde,
  "waterRaster" = waterRaster
  )

parameters<- list(
  .progress = list(type = "text", interval = 1), # for a progress bar
  caribouRSF = list(
    "decidousSp" = c("Betu_Pap", "Popu_Tre", "Popu_Bal"),
  "predictionInterval" = 10)
  )

if (quickPlot::isRstudioServer()) options(httr_oob_default = TRUE)

caribousInit <- simInit(times = times, params = parameters, modules = modules,
                 objects = .objects)

# caribouCall <- spades(caribousInit) # You don't need to run this

library("SpaDES.shiny")
SpaDES.shiny::shine(sim = caribousInit, title = "Caribous in Edehzhie, NWT")

# Quick check on Caribou rasters
presProbList <- lapply(caribous$predictedPresenceProbability, FUN = function(yr){
  return(unlist(yr)[[1]])
})

```

