tb <- structure(list(species = c("Abie_Bal", "Betu_Pap", "Lari_Lar", 
                                 "Pice_Gla", "Pice_Mar", "Pinu_Ban", "Popu_Tre"), 
                     Area = structure(c(5L, 3L, 3L, 3L, 3L, 3L, 3L), 
                                      .Label = c("Acadian", "AM", "BP", "BSE", "BSW", "LSJ", "MC", "NorthShore", "PM", "WestON"), 
                                      class = "factor"),
                     longevity = c(200L, 140L, 350L, 320L, 250L, 250L, 200L),
                     sexualmature = c(30L, 20L, 40L, 30L, 30L, 10L, 20L), 
                     shadetolerance = c(5L, 2L, 1L, 3L, 4L, 1L, 1L), 
                     firetolerance = c(1L, 1L, 1L, 2L, 2L, 2L, 2L), 
                     seeddistance_eff = c(25L, 200L, 50L, 100L, 80L, 30L, 1000L), 
                     seeddistance_max = c(160L, 2000L, 200L, 303L, 200L, 100L, 2000L), 
                     resproutprob = c(0, 0.5, 0, 0, 0, 0, 0.9), 
                     resproutage_min = c(0L, 10L, 0L, 0L, 0L, 0L, 10L), 
                     resproutage_max = c(0L, 70L, 0L, 0L, 0L, 0L, 150L), 
                     postfireregen = structure(c(2L, 3L, 2L, 2L, 4L, 4L, 3L), 
                                               .Label = c("", "none", "resprout", "serotiny"), class = "factor"), 
                     leaflongevity = c(3L, 1L, 1L, 3L, 3L, 2L, 1L), 
                     wooddecayrate = c(0.062, 0.07, 0.02,0.02, 0.02, 0.01, 0.07), 
                     mortalityshape = c(25L, 25L, 25L, 15L, 15L, 25L, 25L), 
                     growthcurve = c(0, 0, 0, 1, 1, 0, 0), 
                     leafLignin = c(0.2, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1), 
                     hardsoft = structure(c(2L, 1L, 2L, 2L, 2L, 2L, 1L), 
                                          .Label = c("hard", "soft"), class = "factor"),
                     speciesCode = structure(1:7, .Label = c("Abie_Bal", "Betu_Pap", 
                                                             "Lari_Lar", "Pice_Gla", "Pice_Mar", "Pinu_Ban", "Popu_Tre"
                     ), class = "factor")), class = c("data.table", "data.frame"
                     ), row.names = c(NA, -7L), sorted = "speciesCode")
