runNamesList <- function(printTable = FALSE){
  library("data.table")
  dt <- data.table(RunName = c("NWT_BCR6",
                               "NWT_Edehzhie",
                               "NWT_NT1_BCR6",
                               "NWT_NT1_BCR6_2011"),
                   Province = c("NWT",
                                "NWT",
                                "NWT",
                                "NWT"),
                   Subregion = c("BCR6",
                                 "Edéhzhíe Protected Area",
                                 "NT1_BCR",
                                 "NT1_BCR"),
                   studyArea = c("https://drive.google.com/open?id=1LUxoY2-pgkCmmNH5goagBp3IMpj6YrdU",
                           "https://drive.google.com/open?id=1fYvNPwovjNtTABoGcegrvdFGkNfCUsxf",
                           "https://drive.google.com/file/d/1RPfDeHujm-rUHGjmVs6oYjLKOKDF0x09/view?usp=sharing",
                           "https://drive.google.com/file/d/1RPfDeHujm-rUHGjmVs6oYjLKOKDF0x09/view?usp=sharing"),
                   rasterToMatch = c("https://drive.google.com/open?id=1fo08FMACr_aTV03lteQ7KsaoN9xGx1Df",
                                     NA,
                                     "https://drive.google.com/file/d/1VMIpeUb2ZTcC9NpQ83YKaWq2sDwwKI8d/view?usp=sharing",
                                     "https://drive.google.com/file/d/1VMIpeUb2ZTcC9NpQ83YKaWq2sDwwKI8d/view?usp=sharing"),
                   studyAreaPSP = c("https://drive.google.com/open?id=18A_HjSx_8viGxz3k87kjra03K6MgsjzO",
                                    "https://drive.google.com/open?id=18A_HjSx_8viGxz3k87kjra03K6MgsjzO",
                                    "https://drive.google.com/open?id=18A_HjSx_8viGxz3k87kjra03K6MgsjzO",
                                    "https://drive.google.com/open?id=18A_HjSx_8viGxz3k87kjra03K6MgsjzO"),
                   watersRaster = c("https://drive.google.com/open?id=1nPd03gaVXkkaHorirR4UhYrDi95ZgyJM",
                                    "https://drive.google.com/open?id=1nPd03gaVXkkaHorirR4UhYrDi95ZgyJM",
                                    "https://drive.google.com/open?id=1nPd03gaVXkkaHorirR4UhYrDi95ZgyJM",
                                    "https://drive.google.com/open?id=1nPd03gaVXkkaHorirR4UhYrDi95ZgyJM"),
                   ecoRegionRaster = c("https://drive.google.com/open?id=1AT2yWbFjAKbY8nPhnwNJ6oviK94_92Pk",
                                       "https://drive.google.com/open?id=1AT2yWbFjAKbY8nPhnwNJ6oviK94_92Pk",
                                       NA,
                                       NA),
                   fireSenseIgnitionFitted = c("https://drive.google.com/open?id=1EetOiGxAq-QTZCVU9Q6Y3I26tqjZm3Oi",
                                               "https://drive.google.com/open?id=1EetOiGxAq-QTZCVU9Q6Y3I26tqjZm3Oi",
                                               "https://drive.google.com/open?id=1EetOiGxAq-QTZCVU9Q6Y3I26tqjZm3Oi",
                                               "https://drive.google.com/open?id=1EetOiGxAq-QTZCVU9Q6Y3I26tqjZm3Oi"),
                   fireSenseEscapeFitted = c("https://drive.google.com/open?id=11CrK9PfNJzkU5cZg9-JYYzyr-VP23W0x",
                                             "https://drive.google.com/open?id=11CrK9PfNJzkU5cZg9-JYYzyr-VP23W0x",
                                             "https://drive.google.com/open?id=11CrK9PfNJzkU5cZg9-JYYzyr-VP23W0x",
                                             "https://drive.google.com/open?id=11CrK9PfNJzkU5cZg9-JYYzyr-VP23W0x"),
                   fireSenseSpreadFitted = c("https://drive.google.com/open?id=1OJB-T72dlqQvjRshs031pxmib4O4H9qN",
                                             "https://drive.google.com/open?id=1OJB-T72dlqQvjRshs031pxmib4O4H9qN",
                                             "https://drive.google.com/open?id=1OJB-T72dlqQvjRshs031pxmib4O4H9qN",
                                             "https://drive.google.com/open?id=1OJB-T72dlqQvjRshs031pxmib4O4H9qN"),
                   fireSenseFolder = c("1yrexBIAROmqDS5PbDia4JJUyzfoIuNxr",
                                       "1yrexBIAROmqDS5PbDia4JJUyzfoIuNxr",
                                       "1yrexBIAROmqDS5PbDia4JJUyzfoIuNxr",
                                       "1yrexBIAROmqDS5PbDia4JJUyzfoIuNxr"),
                   DEoptimCache = c("40927e9ca42d33b3", # Older cacheId for DEOptim (first fireSense run): "56769e2b2edfe8ab" 
                                    "40927e9ca42d33b3",
                                    "40927e9ca42d33b3",
                                    "40927e9ca42d33b3"))
  if (printTable)
    print(dt[, 1:3])
  return(invisible(dt))
}
