---
title: "fireSense_NWT_DataPrep"
author: "Jean Marchal"
date: "06 February 2019"
output: pdf_document
---

# Overview
The purpose of this module is to prepare the climate and vegetation data needed to run the fireSense modules for BCR6 and BCR6 contained in the Northwest Territories.

### Reclassify LCC2005 (39 classes)
LCC05 contains 39 distinct land cover classes:

|Description|Code|
| ------------------------------------------- |-----:|
|Temperate or subpolar needle-leaved evergreen closed tree canopy|1|
|Cold deciduous closed tree canopy|2|
|Mixed needle-leaved evergreen – cold deciduous closed tree canopy|3|
|Mixed needle-leaved evergreen – cold deciduous closed young tree canopy|4|
|Mixed cold deciduous - needle-leaved evergreen closed tree canopy|5|
|Temperate or subpolar needle-leaved evergreen medium density, moss-shrub understory|6|
|Temperate or subpolar needle-leaved evergreen medium density, lichen-shrub understory|7|
|Temperate or subpolar needle-leaved evergreen low density, shrub-moss understory|8|
|Temperate or subpolar needle-leaved evergreen low density, lichen (rock) understory|9|
|Temperate or subpolar needle-leaved evergreen low density, poorly drained|10|
|Cold deciduous broad-leaved, low to medium density|11|
|Cold deciduous broad-leaved, medium density, young regenerating|12|
|Mixed needle-leaved evergreen - cold deciduous, low to medium density|13|
|Mixed cold deciduous - needle-leaved evergreen, low to medium density|14|
|Low regenerating young mixed cover|15|
|High-low shrub dominated|16|
|Grassland|17|
|Herb-shrub-bare cover|18|
|Wetlands|19|
|Sparse needle-leaved evergreen, herb-shrub cover|20|
|Polar grassland, herb-shrub|21|
|Shrub-herb-lichen-bare|22|
|Herb-shrub poorly drained|23|
|Lichen-shrub-herb-bare soil|24|
|Low vegetation cover|25|
|Cropland-woodland|26|
|High biomass cropland|27|
|Medium biomass cropland|28|
|Low biomass cropland|29|
|Lichen barren|30|
|Lichen-sedge-moss-low shrub wetland|31|
|Lichen-spruce bog|32|
|Rock outcrops|33|
|Recent burns|34|
|Old burns|35|
|Urban and Built-up|36|
|Water bodies|37|
|Mixes of water and land|38|
|Snow/ice|39|
\  

which are reclassified by this module as:
\  

|Description|Code|
| ---- | -----:|
|Conifer-HighDensity|1|
|Conifer-MediumDensity|2|
|Conifer-LowDensity|3|
|Crops|4|
|Deciduous|5|
|Disturbed|6|
|Mixed Conifer-dominant|7|
|Mixed Young|8|
|Mixed Hardwood-dominant|9|
|Non-vascular|10|
|Open-conifer|11|
|Shrub|12|
|Wetlands|13|


# Usage

```{r module_usage}
library(SpaDES)

cloudFolderID <- "https://drive.google.com/open?id=1PoEkOkg_ixnAdDqqTQcun77nUvkEHDc0"

setPaths(
  cachePath = "../cache",
  inputPath = "../inputs",
  modulePath = ".."
)

getPaths() # shows where the 4 relevant paths are

start_year <- 1995
end_year <- 2015
times <- list(start = start_year, end = end_year)

parameters <- list(
  fireSense_NWT_DataPrep = list(res = 10000)
)

inputs <- data.frame(
   files = dir(getPaths()$inputPath, pattern = "MDCs_.*_BCR6_NWT_250m[.]tif$"),
   functions = "raster::stack",
   objectName = "MDC_BCR6_NWT_250m",
   loadTime = start_year:end_year
)

objects <- list(
  cloudFolderID = cloudFolderID
)

mySim <- simInit(
  inputs = inputs,
  times = times, 
  params = parameters, 
  modules = list("fireSense_NWT_DataPrep"),
  objects = objects
)

mySimOut <- spades(mySim)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("fireSense_NWT_DataPrep", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

