---
title: "MDC DataPrep"
author: "Jean Marchal"
date: "February, 2019"
output: html_document
---

The purpose of this file is to document how we produced annual Monthly Drought Code (MDC) data.

# Setup
```{r packages, message=FALSE}
library(dplyr)
library(ff)
library(ffbase)
library(raster)
library(reproducible)
library(sf)
library(sp)
library(tibble)
library(tidyselect)

options(reproducible.overwrite = TRUE)
knitr::opts_chunk$set(eval = FALSE)

climateNA_Outputs_FD <- "F:/NWT/Climate/" # Folder where climateNA_outputs are stored

SpaDES_Input_Dir <- "../inputs"

if(!dir.exists(SpaDES_Input_Dir))
{
  dir.create(SpaDES_Input_Dir)
}
```

# Prepare ClimateNA inputs - 250m and 1km resolution
```{R}
#
# Need to have 3 things: lat, long, elevation
#
#
## Load BCR6_RT, raster version of the BCR6 study area
##      BCR6_NWT_RT, raster version of the BCR6 as contained in the Northwest territories
##      DEM_BCR6, Digital elevation model for BCR6
##      DEM_BCR6_NWT, Digital elevation model for BCR6 as contained in the Northwest territories
#

# BCR6_RT
BCR6_250m <- Cache(
  prepInputs,
  url = "https://drive.google.com/open?id=1sEiXKnAOCi-f1BF7b4kTg-6zFlGr0YOH",
  targetFile = "bcr6.tif"
)

# BCR6_NWT_RT
BCR6_NWT_RT <- Cache(
  prepInputs,
  url = "https://drive.google.com/open?id=1NIjFbkckG3sewkTqPGaBGQDQLboPQ0wc"
)

# DEM_BCR6
DEM_250m <- Cache(
  prepInputs,
  url = "https://drive.google.com/open?id=1_7L8QDozDtGSuYWBKKkgzCABocR9lWVN"
)

# DEM_BCR6_NWT
DEM_BCR6_NWT <- Cache(
  prepInputs,
  url = "https://drive.google.com/open?id=1SKnXVqUD10_VdemQaPaz9MrWiNZzK7VY"
)

#
## Produce 1km versions of BCR6 and DEM
#
BCR6_1km <- Cache(
  aggregate,
  BCR6_NWT_RT,
  fact = 4
)

DEM_1km <- Cache(
  postProcess,
  DEM_BCR6_NWT,
  method = "bilinear",
  rasterToMatch = BCR6_1km,
  maskWithRTM = TRUE,
  filename2 = NULL
)

prep_ClimateNA_inputs <- function(res)
{
  BCR6 <- get(paste0("BCR6_", res))
  DEM <- get(paste0("DEM_", res))
  
  withinBCR6 <- !is.na(BCR6[])
  elev <- DEM[withinBCR6]
  
  #
  ## Parts of the BCR6 where we have no data, after manual inspection, they are pixels
  ## in the sea. Confirmed by Diana. Remove these pixels from BCR6.
  #
  withinBCR6 <- which(withinBCR6)[!is.na(elev)]
  elev <- elev[!is.na(elev)]
  
  #
  # Write lat, long, elev to csv
  #
  np <- 8 # Split in 8 parts to stay within memory limits and because we have 8 threads available...
  wp <- rep(1:np, length.out = length(elev))
  
  for (i in 1:np)
  {
    f <- file(
      paste0("climateNA_inputs", i, "_", res, ".csv"), 
      "wb" # Use binary mode to prevent OS dependent behaviour for eol
    )
    
    write.csv(
      (
        bind_cols(
          (
            st_as_sf(
              as_tibble(
                raster::xyFromCell(BCR6, withinBCR6[wp == i])
              ),
              coords = c("x", "y"),
              crs = proj4string(DEM)
            ) %>%
              st_transform(crs = 4326) %>%
              st_coordinates() %>%
              as_tibble() %>%
              rename(lat = Y, long = X)
          ),
          tibble(el = elev[wp == i])
        ) %>%
          mutate(ID1 = withinBCR6[wp == i], ID2 = "") %>%
          dplyr::select(ID1, ID2, lat, long, el)
      ),
      file = f,
      row.names = FALSE,
      eol = "\r\n" # ClimateNA is windows software
    )
    
    close(f)
  }
}

rasterOptions(chunksize = 1e10) # Otherwise takes ages!

prep_ClimateNA_inputs("250m")
prep_ClimateNA_inputs("1km")
```

# Read and filter ClimateNA outputs
Climate variables are described in the [AdaptWest paper](https://dx.doi.org/10.1371/journal.pone.0156720)
```{R, message=FALSE}
read_ClimateNA_outputs <- function(files)
{
  climateNA_outputs <- do.call(
    "ffdfrbind.fill",
    lapply(
      files,
      function(file)
      {
        climateNA_outputs <- read.csv.ffdf(
          file = file,
          header = TRUE,
          colClasses = c("integer", "integer", "factor", rep("numeric", 171)),
          first.rows = 1e6,
          next.rows = 1e6,
          VERBOSE = TRUE
        )
        
        climateNA_outputs <- climateNA_outputs[
          vars_select(
            colnames(climateNA_outputs), 
            Year, ID1, Latitude, Longitude, 
            num_range("Tmax", 4:9, 2), num_range("PPT",  4:9, 2)
          )
        ]
      }
    )
  )
  
  # Re-encode NoData, they were encoded as -9999
  for (i in 4:9)
  {
    climateNA_outputs[[paste0("Tmax0", i)]][climateNA_outputs[[paste0("Tmax0", i)]][] == -9999] <- NA
    climateNA_outputs[[paste0("PPT0", i)]][climateNA_outputs[[paste0("PPT0", i)]][] == -9999] <- NA
  }

  climateNA_outputs
}

climateNA_outputs_250m <- read_ClimateNA_outputs(
  dir(
    path = climateNA_Outputs_FD, 
    pattern = "climateNA_outputs.*_250m[.]csv$", 
    full.names = TRUE
  )
)

# climateNA_outputs_1km <- read_ClimateNA_outputs(
#   dir(
#     path = climateNA_Outputs_FD, 
#     pattern = "climateNA_outputs.*_1km[.]csv$", 
#     full.names = TRUE
#   )
# )
```

# Calculate MDC (April - September)
Calculate the Monthly Drought Code following [Bergeron et al. 2010](https://dx.doi.org/10.1071/WF09092):

$$Q = 800e^{-DC/400}$$
$$E_m = n(0.36(\bar{T}_{mx}) + L_f)$$
$$DC_{HALF} = MDC_0 + 0.25E_m$$
$$Q_{mr} = 3.937RM_{EFF}/800e^{-MDC_0/400}$$
$$DC_{mr} = DC_{HALF} - 400ln(1+Q_{mr})$$
$$MDC_m = DC_{mr} + 0.25E_m$$
$$MDC = (MDC_0 + MDC_m) / 2$$

Abbreviations:

  * $DC_{HALF}$: drying taking place over the first half of the month
  * $DC_{mr}$: drying taking place over the middle of the month
  * $MDC_0$: MDC from the end of the previous month
  * $MDC_m$: MDC at the end of the month
  * $E_m$: evapotranspiration over month
  * $L_f$: standard day-length adjustement factor
  * $n$: number of days in the month
  * $Q$: moisture equivalent
  * $Q_{mr}$: moisture equivalent in the layer after rain
  * $r_m$: total monthly rainfall
  * $RM_{EFF}$: effective rainfall
  * $T_{mx}$: monthly mean of daily max temperatures

```{R}
calc_MDC <- function(climateNA_outputs)
{
  # Day length adjustement L_f in Drought Code (taken from Van Wagner 1987)
  L_f <- function(month)
  {
    c(
      '4' = 0.9, 
      '5' = 3.8,
      '6' = 5.8, 
      '7' = 6.4, 
      '8' = 5.0,
      '9' = 2.4
    )[[as.character(month)]]
  }
  
  MDC_0 <- ff(0, length = nrow(climateNA_outputs))
  
  for (i in 4:9)
  {
    climateNA_outputs[[paste0("MDC0", i)]] <- MDC_0 <- 
      ffvecapply(
        {
          n <- c(
            '4' = 30, 
            '5' = 31,
            '6' = 30, 
            '7' = 31, 
            '8' = 31,
            '9' = 30
          )[[as.character(i)]]
          
          T_mx <- climateNA_outputs[[paste0("Tmax0", i)]][i1:i2] # Max monthly temperature
          r_m <- climateNA_outputs[[paste0("PPT0", i)]][i1:i2]   # Total monthly precip
          
          MDC_m <- pmax(
            MDC_0[i1:i2] + .25 * n * (.36 * T_mx + L_f(i)) -
              400 * log(1 + 3.937 * .83 * r_m / (800 * exp(-MDC_0[i1:i2]/400))) +
              .25 * n * (.36 * T_mx + L_f(i)), 
            0
          )
          
          pmax((MDC_0[i1:i2] + MDC_m) / 2, 0)
        },
        X = climateNA_outputs[[paste0("Tmax0", i)]], 
        RETURN = TRUE, 
        VMODE = "double"
      )
  }
  
  climateNA_outputs[
    vars_select(
      colnames(climateNA_outputs), 
      Year, ID1, num_range("MDC", 4:9, 2)
    )
  ]
}

MDC_250m <- Cache(calc_MDC, climateNA_outputs_250m)
# MDC_1km <- Cache(calc_MDC, climateNA_outputs_1km)
```

### Produce and save MDC rasters for the 1995-2015 period, BCR6 and BCR6 as contained in the NWT, 250m resolution
``` {R}
save_MDC_RT <- function(res)
{
  BCR6 <- get(paste0("BCR6_", res))
  MDC <- get(paste0("MDC_", res))
  
  for (year in 1995:2015)
  {
    lapply(
      4:9,
      function(month_i)
      {
        BCR6[MDC[MDC[["Year"]] == year, "ID1"][]] <-
               MDC[MDC[["Year"]] == year, paste0("MDC0", month_i)][]
        print(
          writeRaster(
            BCR6, 
            filename = paste0("MDC0", month_i, "_", year, "_BCR6_", res, ".tif"),
            overwrite = TRUE,
            datatype = "FLT4S"
          )
        )
        
        Cache(
          postProcess,
          BCR6,
          rasterToMatch = BCR6_NWT_RT,
          maskWithRTM = TRUE,
          filename2 = paste0("MDC0", month_i, "_", year, "_BCR6_NWT_", res, ".tif"),
          datatype = "FLT4S",
          method = "bilinear",
          overwrite = TRUE
        )
      }
    )
  }
}

save_MDC_RT("250m")
```

### For each year stack the rasters of each month (April to September), 250m resolution
```{R}
for (year in 1995:2015)
{
  writeRaster(
    stack(
      lapply(
        dir(pattern = paste0("MDC0[4-9]_", year, "_BCR6_NWT_250m[.]tif$")),
        raster
      )
    ),
    datatype = "FLT4S",
    filename = file.path(SpaDES_Input_Dir, paste0("MDCs_", year, "_BCR6_NWT_250m.tif")),
    overwrite = TRUE
  )
}
```