---
title: "birdsPosthoc"
author: "tmichele"
date: "29 October 2019"
output: pdf_document
---

# Overview

Provide an overview of what the module does / how to use the module.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
  library("SpaDES")
  library("future")
  library("future.apply")
  plan("multiprocess")
  devtools::load_all("/mnt/data/Micheletti/usefun/")
  
  if (pemisc::user() %in% c("Tati", "tmichele"))
    setwd("/mnt/data/Micheletti/NWT")
  
  setPaths(modulePath = file.path(getwd(), "modules"),
           inputPath = file.path(getwd(), "outputs/23OCT19/"),
           outputPath = checkPath(file.path(getwd(), "outputs/23OCT19/birdResults"), create = TRUE)
  )
  getPaths() # shows where the 4 relevant paths are
  
  times <- list(start = 1, end = 1)
  Run <- "run1"
  
    inputs <- list()
  outputs <- data.frame(
    objectName = c("deltaRasters",
                   "significantChanges",
                   "pixelsSummaries"),
    saveTime = times$end)

  doCaribou <- TRUE
  doBirds <- FALSE
  
  #  ~~~~~~~~~~~~~~~~~~~~~~~~# FOR BIRDS #~~~~~~~~~~~~~~~~~~~~~~~~
  
  if (doBirds){
     species <- c("RUBL", "CAWA", "OSFL", "BBWA", "WEWP")
  parameters <- list(
    rastersPosthoc = list(patternsToRetrieveRasters = c("predicted", "Year", "tif"),
                          patternsUsedForGrouping = species,
                          years = c(seq(2011, 2100, by = 30), 2100),
                          species = species, 
                          n = 50,
                          sampleSize = 45,
                          comparisonID = "Birds",
                          uploadPlots = TRUE)
    )
  modules <- list("rastersPosthoc")
  objectsV6 <- list(dataFolder = list(
                  LandR.CS_fS_V6 = file.path(getPaths()$inputPath, "LandR.CS_fS", Run, "birdPredictions"),
                  LandR_fS_V6 = file.path(getPaths()$inputPath, "LandR_fS", Run, "birdPredictions"),
                  LandR.CS_SCFM_V6 = file.path(getPaths()$inputPath, "LandR.CS_SCFM", Run, "birdPredictions"),
                  LandR_SCFM_V6 = file.path(getPaths()$inputPath, "LandR_SCFM", Run, "birdPredictions")),
                  googleFolders = list(
                    LandR.CS_fS <- "1ooFQ4IbkVtVL3topEvz_3vAMu-6h-hyB",
                    LandR.CS_SCFM <- "1Nuo091FmyFnrfLKVvQXjGoTN8fRUfXIJ",
                    LandR_fS <- "1PmQR0SkNOrfi5fq_a16PTmsYoLw8zSJJ",
                    LandR_SCFM <- "1A6BslpcPi4D_9bZ_2DC7sgEXz447cuRv"
                    )
                  )
  objectsV3 <- list(dataFolder = list(
                  LandR.CS_fS_V3 = file.path(getPaths()$inputPath, "LandR.CS_fS", Run, "birdPredictionsV3"),
                  LandR_fS_V3 = file.path(getPaths()$inputPath, "LandR_fS", Run, "birdPredictionsV3"),
                  LandR.CS_SCFM_V3 = file.path(getPaths()$inputPath, "LandR.CS_SCFM", Run, "birdPredictionsV3"),
                  LandR_SCFM_V3 = file.path(getPaths()$inputPath, "LandR_SCFM", Run, "birdPredictionsV3")),
                  googleFolders = list(
                    LandR.CS_fS <- "1ooFQ4IbkVtVL3topEvz_3vAMu-6h-hyB",
                    LandR.CS_SCFM <- "1Nuo091FmyFnrfLKVvQXjGoTN8fRUfXIJ",
                    LandR_fS <- "1PmQR0SkNOrfi5fq_a16PTmsYoLw8zSJJ",
                    LandR_SCFM <- "1A6BslpcPi4D_9bZ_2DC7sgEXz447cuRv"
                    )
                  )
  
birdV3 <- simInit(times = times, params = parameters, modules = modules,
                   objects = objectsV3, outputs = outputs)
 
birdV6 <- simInit(times = times, params = parameters, modules = modules,
                  objects = objectsV6)
                  
birdResults <- spades(birdV3, debug = 1)
  }
  
  #  ~~~~~~~~~~~~~~~~~~~~~~~~# FOR CARIBOUS #~~~~~~~~~~~~~~~~~~~~~~~~
if (doCaribou){
  typeOfRas <- c("SelectionTaiga", "SelectionUncertainTaiga")
  parameters <- list(
    rastersPosthoc = list(patternsToRetrieveRasters = c("relativeSelection", "Year", "tif"),
                          patternsUsedForGrouping = typeOfRas,
                          years = c(2011, 2041, 2071, 2100),
                          species = typeOfRas, 
                          n = 50,
                          sampleSize = 45,
                          comparisonID = "Caribou",
                          uploadPlots = TRUE,
                          calculateSignificantChanges = FALSE,
                          calculateSummary = FALSE)
    )
  modules <- list("rastersPosthoc")
  objectsCaribou <- list(dataFolder = list(
                  LandR.CS_fS = file.path(getPaths()$inputPath, "LandR.CS_fS", Run, "caribouPredictions"),
                  LandR_fS = file.path(getPaths()$inputPath, "LandR_fS", Run, "caribouPredictions"),
                  LandR.CS_SCFM = file.path(getPaths()$inputPath, "LandR.CS_SCFM", Run, "caribouPredictions"),
                  LandR_SCFM = file.path(getPaths()$inputPath, "LandR_SCFM", Run, "caribouPredictions")),
                  googleFolders = list(
                    LandR.CS_fS <- "1ooFQ4IbkVtVL3topEvz_3vAMu-6h-hyB",
                    LandR.CS_SCFM <- "1Nuo091FmyFnrfLKVvQXjGoTN8fRUfXIJ",
                    LandR_fS <- "1PmQR0SkNOrfi5fq_a16PTmsYoLw8zSJJ",
                    LandR_SCFM <- "1A6BslpcPi4D_9bZ_2DC7sgEXz447cuRv"
                    )
                  )

boo <- simInitAndSpades(times = times, params = parameters, modules = modules,
                   objects = objectsCaribou, outputs = outputs)
}

  # Testing experiment -- currently (5th nov not working as I can't install it)

#   objectsCaribou_CSfS <- list(dataFolder = list(
#                   LandR.CS_fS = file.path(getPaths()$inputPath, "LandR.CS_fS", Run, "caribouPredictions"))
#                   )
#   objectsCaribou_fS <- list(dataFolder = list(
#                   LandR_fS = file.path(getPaths()$inputPath, "LandR_fS", Run, "caribouPredictions"))
#                   )
#     objectsCaribou_CSSCFM <- list(dataFolder = list(
#                   LandR.CS_SCFM = file.path(getPaths()$inputPath, "LandR.CS_SCFM", Run, "caribouPredictions"))
#                   )
#   objectsCaribou_SCFM <- list(dataFolder = list(
#                   LandR_SCFM = file.path(getPaths()$inputPath, "LandR_SCFM", Run, "caribouPredictions"))
#                   )
# 
# CS_fS <- simInit(times = times, params = parameters, modules = modules,
#                    objects = objectsCaribou_CSfS, outputs = outputs)
# fS <- simInit(times = times, params = parameters, modules = modules,
#                    objects = objectsCaribou_fS, outputs = outputs)
# CS_SCFM <- simInit(times = times, params = parameters, modules = modules,
#                    objects = objectsCaribou_CSSCFM, outputs = outputs)
# SCFM <- simInit(times = times, params = parameters, modules = modules,
#                    objects = objectsCaribou_SCFM, outputs = outputs)
# 
# BooResults <- experiment2(CS_fS, fS, CS_SCFM, SCFM, debug = 1)
# 
# library(SpaDES.experiment)
# birdResults <- experiment2(birdV6, birdV3)

# devtools::install_github("PredictiveEcology/SpaDES.experiment@development")
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("birdsPosthoc", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

