---
title: "LandR_BiomassGMOrig"
author: ""
date: "02 March 2017"
output: pdf_document
---

# Overview

LandR_BiomassGMOrig simulates vegetation growth and mortality processes. The functions that determine growth and mortality are unchanged from LANDIS-II, however the parameters that constrain them may differ, e.g. maximum biomass and annual primary productivity. In LANDIS-II, maximum biomass is defined as max(B) = 30 * ANPPmax, where ANPPmax is the user-supplied maximum annual net primary productivity, whereas in LANDR maximum biomass may now be parameterized separately. Growth and mortality dynamics are simulated in units of biomass (g/m2) for each cohort within a stand at an annual timestep. 

Growth is dependent upon the maximum annual primary productivity of a species, cohort age, and competition. Species-specific growth curves dictate the maximum growth for a cohort as it ages. Young cohorts have lower maximum growth,  as small trees are not as productive as large, mature trees. Competition acts to reduce growth by limiting the available growing space, while recent disturbances (ie last year's disturbances) increase the available growing space.

Mortality is derived from two sources, senescence and development-related mortality, the ongoing loss of individual trees and branches (Scheller and Mladenoff, 2004). It is limited by the maximum biomass of a cohort. As cohorts near their longevity age, age-related mortality increases, eventually reaching the entirety of the cohort's biomass at the maximum lifespan of the cohort species.  

References: 
Scheller, R. M. and Mladenoff, D. J. A forest growth and biomass module for a landscape simulation model, LANDIS: Design, validation, and application. Ecological Modelling. 2004; 180(1):211-229. 

## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
library(igraph)
library(SpaDES)

moduleDir <- file.path("C:/Users/yonluo/Documents/GitHub/LBMR_ClimateSensitive")
inputDir <- file.path(moduleDir, "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(moduleDir, "outputs")
cacheDir <- file.path(outputDir, "cache")
times <- list(start = 0, end = 10)
parameters <- list(
  #.progress = list(type = "text", interval = 1), # for a progress bar
  ## If there are further modules, each can have its own set of parameters:
  #module1 = list(param1 = value1, param2 = value2),
  #module2 = list(param1 = value1, param2 = value2)
)
modules <- list("LandR_BiomassGMOrig")
objects <- list()
paths <- list(
  cachePath = cacheDir,
  modulePath = moduleDir,
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)

spades(mySim)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("LandR_BiomassGMOrig", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

